{
    'name': 'Intranet SRM-TTA',
    'version': '19.0.1.0.0',
    'category': 'Tools',
    'author': 'SRM-TTA',
    'depends': ['base', 'web'],
    'data': [
        'security/ir.model.access.csv',
        'views/menu.xml',
        'views/pole_views.xml',
        'views/direction_views.xml',
        'views/direction_p_views.xml',
        'views/direction_new_views.xml',
        'views/sub_direction_views.xml',
        'views/news_views.xml',
        'views/document_views.xml',
        'views/feedback_views.xml',
        'views/user_views.xml',
        'data/cron_data.xml',
        'data/demo_data.xml',
    ],
    'installable': True,
    'application': True,
}
