[options]
; Odoo Configuration File

; Server
admin_passwd = admin
db_host = localhost
db_port = 5432
db_user = odoo
db_password = odoo

; Addons Paths (add your custom addons path here)
addons_path = E:\Odoo19\server\odoo\addons,C:\Users\DELL\srm-work\backend\odoo\addons
; Log
logfile = False
log_level = info

; Workers
workers = 0
max_cron_threads = 1

; Security
list_db = True
proxy_mode = False

; Timeout
limit_time_cpu = 60
limit_time_real = 120
limit_memory_hard = 2684354560
limit_memory_soft = 2147483648

; Database
db_maxconn = 64
db_name = srm_dev
dbfilter = ^srm_dev$

; Email
smtp_port = 587
smtp_ssl = True
smtp_user = False
smtp_password = False

; Session
session_timeout = 3600
