from . import direction
from . import direction_new
from . import sub_direction
from . import news
from . import document
from . import feedback
from . import helpdesk_ticket
from . import pole
from . import user
from . import formation
from . import inscription
from . import suggestion
from . import kpi
from . import mappage_kpi
